[package]
name = "blog_os"
version = "0.1.0"
authors = ["Sorrow17 <sorrow17@outlook.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
